name: .NET Framework CI

on:
  push:
    branches: [ "main", "модульные тесты pr5" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ConsoleApp46.sln

    - name: Build solution
      run: msbuild ConsoleApp46.sln /p:Configuration=Release

    - name: Run tests
      run: |
        vstest.console.exe **\bin\Release\*Tests*.dll
